language: ruby

rvm:
  - 2.0.0
  - 1.9.3
  
before_script:
  - cp config/database.sample.yml config/database.yml
  - rake db:create
  - rake db:migrate
  - rake db:rollback STEP=1000
  - rake db:migrate
  - rake db:test:prepare
  - rake db:seed
