mysql: &defaults
  adapter: mysql2
  username: root
  password:
  pool: 5
  timeout: 5000
  host: localhost

development:
  database: slingshot_dev
  <<: *defaults

test:
  database: slingshot_test
  <<: *defaults

production:
  database: slingshot_prod
  <<: *defaults